### PR TITLE
Refactor to a module system

### PR DESCRIPTION
**Pull request by ehmry**
A simple conversion. More options can be added later.

### CODE REVIEW

**Comment by astro** [comment]
>We will need to generate a manual to make this usuable.

Generate a manual from NixOS options? I could use this for even more 
projects.

**Comment by ehmry** [comment]
Hash updates are a pain, it would be nice to specify those in a module as well.

**Comment by adamcstephens** [comment]
@ehmry did you give up on this (and the UCI PR)?

**Comment by ehmry** [comment]
Pretty much. I moved the code here: https://gitea.c3d2.de/ehmry/nix-openwrt-imagebuilder

**Comment by astro** [comment]
Uh, but I liked this PR!

**Pull request closed without merging**
